# -*- coding: utf-8 -*-
"""Content of the 8 service pages before they became editable (used to seed wasm.service)."""

SERVICES = [{'card_num': 1,
  'title_en': 'Planning & Structural Construction',
  'title_ar': 'التخطيط والإنشاءات الخرسانية',
  'subtitle_en': 'ARFA SPECIALIZED SYSTEMS offers full-scale engineering management, structural design, and general contracting services for complex '
                 'residential, commercial, industrial, and healthcare developments.',
  'subtitle_ar': 'تقدم شركة عرفة للأنظمة المتخصصة إدارة هندسية وتصميم إنشائي ومقاولات عامة للمشاريع السكنية والتجارية والصناعية والصحية.',
  'icon': 'fa-building',
  'bg_img': '/wasm_website/static/src/img/official_live_services/planning-construction_img_1.webp',
  'badge_en': 'Structural Design & General Contracting',
  'badge_ar': 'التصميم الإنشائي والمقاولات العامة',
  'features_en': ['Full-scale engineering management & structural design for complex developments.',
                  'General contracting across residential, commercial, industrial, & healthcare sectors.',
                  'Value engineering, strict quality control, and schedule management.',
                  'Resilient, modern structures built to the highest Saudi Building Code (SBC) standards.'],
  'features_ar': ['إدارة هندسية وتصميم إنشائي متكامل للمشاريع المعقدة.',
                  'تنفيذ الأعمال الإنشائية والمقاولات العامة لكافة القطاعات.',
                  'الهندسة القيمية والرقابة الصارمة على الجودة والجداول الزمنية.',
                  'مبانٍ وبنى حديثة ومقاومة وفق أعلى معايير كود البناء السعودي SBC.'],
  'gallery_imgs': ['/wasm_website/static/src/img/official_live_services/planning-construction_img_1.webp',
                   '/wasm_website/static/src/img/official_live_services/planning-construction_img_2.webp',
                   '/wasm_website/static/src/img/official_live_services/planning-construction_img_3.webp',
                   '/wasm_website/static/src/img/official_live_services/planning-construction_img_4.webp',
                   '/wasm_website/static/src/img/official_live_services/planning-construction_img_5.webp',
                   '/wasm_website/static/src/img/official_live_services/planning-construction_img_6.webp'],
  'slug': 'planning-construction'},
 {'card_num': 2,
  'title_en': 'Electromechanical Systems (MEP)',
  'title_ar': 'أنظمة الكهروميكانيك (MEP)',
  'subtitle_en': 'ARFA SPECIALIZED SYSTEMS boasts a highly qualified engineering and technical team specializing in the design, execution, and '
                 'maintenance of complete MEP infrastructure.',
  'subtitle_ar': 'تتميز شركة عرفة للأنظمة المتخصصة بكادر هندسي وفني عالي التأهيل متخصص في تصميم وتنفيذ وصيانة شبكات الكهروميكانيك.',
  'icon': 'fa-bolt',
  'bg_img': '/wasm_website/static/src/img/official_live_services/electromechanical-systems_img_1.webp',
  'badge_en': 'Complete MEP Engineering',
  'badge_ar': 'حلول الكهروميكانيك المتقدمة',
  'features_en': ['Central air conditioning, cooling plants, and precision ductwork systems.',
                  'Plumbing infrastructure, drainage networks, and swimming pool construction.',
                  'Firefighting, FM-200 / CO2 gas fire suppression, and alarm systems.',
                  'BMS Systems, electrical distribution, power transformers, and low-voltage networks.'],
  'features_ar': ['أنظمة التكييف المركزي ومحطات التبريد وإمدادات الدكت.',
                  'شبكات السباكة وتصريف المياه وإنشاء حمامات السباحة.',
                  'أنظمة إطفاء الحريق والإغمار بالغاز وشبكات الإنذار المبكر.',
                  'أنظمة BMS والتحكم الكهربائي ومحطات الجهد المنخفض.'],
  'gallery_imgs': ['/wasm_website/static/src/img/official_live_services/electromechanical-systems_img_1.webp',
                   '/wasm_website/static/src/img/official_live_services/electromechanical-systems_img_2.webp',
                   '/wasm_website/static/src/img/official_live_services/electromechanical-systems_img_3.webp',
                   '/wasm_website/static/src/img/official_live_services/electromechanical-systems_img_4.webp',
                   '/wasm_website/static/src/img/official_live_services/electromechanical-systems_img_5.webp',
                   '/wasm_website/static/src/img/official_live_services/electromechanical-systems_img_6.webp'],
  'slug': 'electromechanical-systems'},
 {'card_num': 3,
  'title_en': 'Smart Building Systems (BMS)',
  'title_ar': 'أنظمة المباني الذكية (BMS)',
  'subtitle_en': 'ARFA SPECIALIZED SYSTEMS implements smart building solutions across residential and commercial developments, enabling clients to '
                 'effortlessly control and manage all integrated systems remotely.',
  'subtitle_ar': 'تطبق شركة عرفة للأنظمة المتخصصة حلول المباني الذكية في المشاريع السكنية والتجارية لتمكين التحكم والتعديل عن بُعد.',
  'icon': 'fa-microchip',
  'bg_img': '/wasm_website/static/src/img/official_live_services/smart-building-systems_img_1.webp',
  'badge_en': 'Building Automation & Remote Control',
  'badge_ar': 'أتمتة المباني والتحكم الرقمي',
  'features_en': ['Integrated BMS for centralized energy, climate, and smart lighting control.',
                  'Remote management of facility operations with minimal human intervention.',
                  'IP CCTV surveillance integration and biometric access control systems.',
                  'Real-time automated diagnostic monitoring and predictive maintenance sensors.'],
  'features_ar': ['أنظمة BMS المركزية لإدارة الطاقة والإضاءة والتكييف الذكي.',
                  'التحكم والتعديل عن بُعد بالمنشآت مع تقليل التدخل البشرى.',
                  'ربط أنظمة المراقبة الرقمية CCTV وبوابات الدخول المغناطيسية.',
                  'مراقبة تشخيصية فورية للتنبيه بالأعطال والصيانة التنبؤية.'],
  'gallery_imgs': ['/wasm_website/static/src/img/official_live_services/smart-building-systems_img_1.webp',
                   '/wasm_website/static/src/img/official_live_services/smart-building-systems_img_2.webp',
                   '/wasm_website/static/src/img/official_live_services/smart-building-systems_img_3.webp',
                   '/wasm_website/static/src/img/official_live_services/smart-building-systems_img_4.webp',
                   '/wasm_website/static/src/img/official_live_services/smart-building-systems_img_5.webp',
                   '/wasm_website/static/src/img/official_live_services/smart-building-systems_img_6.webp'],
  'slug': 'smart-building-systems'},
 {'card_num': 4,
  'title_en': 'Modern Building Systems & Prefab',
  'title_ar': 'الأنظمة الحديثة والمباني (Prefab)',
  'subtitle_en': 'ARFA SPECIALIZED SYSTEMS is one of the leading companies to adopt modern building systems across all construction departments, '
                 'reducing overall costs and maximizing resource efficiency.',
  'subtitle_ar': 'تعتبر شركة عرفة للأنظمة المتخصصة من الشركات الرائدة في تبني أنظمة البناء الحديثة لتقليل التكاليف وزيادة الكفاءة.',
  'icon': 'fa-cubes',
  'bg_img': '/wasm_website/static/src/img/official_live_services/modern-building-systems_img_1.webp',
  'badge_en': 'Fast & Sustainable Construction Tech',
  'badge_ar': 'تقنيات البناء الحديثة والمستدامة',
  'features_en': ['Adoption of advanced modern building systems across all construction sectors.',
                  'Maximized efficiency of modern building resources reducing total development costs.',
                  'Structural glass facades, curtain walls, and premium aluminum cladding.',
                  'Prefabricated modular building methods with superior thermal insulation.'],
  'features_ar': ['تبني أحدث تقنيات وأنظمة البناء الحديثة بكافة قطاعات التشييد.',
                  'تعظيم كفاءة الموارد الحديثة وتقليل التكلفة الإجمالية للمشاريع.',
                  'تركيب الواجهات الزجاجية والهياكل المعدنية والألومنيوم الفاخر.',
                  'أنظمة البناء مسبق الصنع المودولار بأعلى مستويات العزل الحراري.'],
  'gallery_imgs': ['/wasm_website/static/src/img/official_live_services/modern-building-systems_img_1.webp',
                   '/wasm_website/static/src/img/official_live_services/modern-building-systems_img_2.webp',
                   '/wasm_website/static/src/img/official_live_services/modern-building-systems_img_3.webp',
                   '/wasm_website/static/src/img/official_live_services/modern-building-systems_img_4.webp',
                   '/wasm_website/static/src/img/official_live_services/modern-building-systems_img_5.webp',
                   '/wasm_website/static/src/img/official_live_services/modern-building-systems_img_6.webp'],
  'slug': 'modern-building-systems'},
 {'card_num': 5,
  'title_en': 'Fire Protection & Prevention Systems',
  'title_ar': 'أنظمة الوقاية والحماية من الحريق',
  'subtitle_en': 'ARFA SPECIALIZED SYSTEMS designs, installs, and maintains high-performance fire protection and prevention systems adhering '
                 'strictly to Civil Defense regulations and NFPA, UL, and FM standards.',
  'subtitle_ar': 'تصمم وتنفذ وتصين شركة عرفة للأنظمة المتخصصة أنظمة السلامة والوقاية من الحريق المعتمدة من الدفاع المدني والمعايير الدولية (NFPA, '
                 'UL, FM).',
  'icon': 'fa-fire-extinguisher',
  'bg_img': '/wasm_website/static/src/img/official_live_services/fire-protection-prevention-systems_img_1.webp',
  'badge_en': 'Civil Defense & NFPA Certified Safety',
  'badge_ar': 'معتمدة من الدفاع المدني وNFPA',
  'features_en': ['Smart addressable fire alarm, smoke detection, and aspirating early-warning networks.',
                  'Automatic sprinkler networks, deluge systems, and UL/FM fire pump stations.',
                  'Clean agent gas suppression (FM-200, CO2, Novec 1230) for server rooms and data centers.',
                  'Testing, commissioning, and official Saudi Civil Defense licensing certification.'],
  'features_ar': ['شبكات إنذار كشف الدخان والتنبيه المبكر المعنونة.',
                  'شبكات الرش الآلي ومحطات مضخات الحريق المعيارية UL/FM.',
                  'أنظمة الإطفاء التلقائي بالغازات النظيفة لغرف البيانات والمعدات.',
                  'اختبارات التشغيل واختبار الضغط وتراخيص الدفاع المدني المعتمدة.'],
  'gallery_imgs': ['/wasm_website/static/src/img/official_live_services/fire-protection-prevention-systems_img_1.webp',
                   '/wasm_website/static/src/img/official_live_services/fire-protection-prevention-systems_img_2.webp',
                   '/wasm_website/static/src/img/official_live_services/fire-protection-prevention-systems_img_3.webp',
                   '/wasm_website/static/src/img/official_live_services/fire-protection-prevention-systems_img_4.webp',
                   '/wasm_website/static/src/img/official_live_services/fire-protection-prevention-systems_img_5.webp',
                   '/wasm_website/static/src/img/official_live_services/fire-protection-prevention-systems_img_6.webp'],
  'slug': 'fire-protection-prevention-systems'},
 {'card_num': 6,
  'title_en': 'Medical Gas Systems (MGPS)',
  'title_ar': 'أنظمة الغازات الطبية (MGPS)',
  'subtitle_en': 'ARFA SPECIALIZED SYSTEMS provides end-to-end engineering solutions for Medical Gas Pipeline Systems (MGPS) in healthcare '
                 'facilities according to strict HTM 02-01 / NFPA 99 standards.',
  'subtitle_ar': 'تقدم شركة عرفة للأنظمة المتخصصة حلولاً هندسية متكاملة لشبكات الغازات الطبية بالمنشآت الصحية وفق معايير HTM 02-01 وNFPA 99.',
  'icon': 'fa-medkit',
  'bg_img': '/wasm_website/static/src/img/official_live_services/medical-gas-systems_img_1.webp',
  'badge_en': 'HTM 02-01 / NFPA 99 Hospital Standards',
  'badge_ar': 'معايير المستشفيات العالمية HTM/NFPA',
  'features_en': ['Medical Gas Pipeline Systems (MGPS) for hospitals and specialized medical centers.',
                  'Central oxygen supply stations, surgical air, and high-vacuum plant installations.',
                  'Bedhead units (BHU), ICU monitoring panels, and digital gas pressure alarms.',
                  'Full testing and clinical safety compliance to HTM 02-01 and NFPA 99 code.'],
  'features_ar': ['شبكات تمديد الغازات الطبية المركزية للمستشفيات والجهات الصحية.',
                  'محطات الأكسجين المركزية وضواغط الهواء والمطارد الجراحية.',
                  'وحدات رؤوس الأسرة (BHU) ولوحات المراقبة الرقمية لغرف العناية.',
                  'اختبارات النقاء والضغط والاعتماد الطبي وفق HTM 02-01 وNFPA 99.'],
  'gallery_imgs': ['/wasm_website/static/src/img/official_live_services/medical-gas-systems_img_1.webp',
                   '/wasm_website/static/src/img/official_live_services/medical-gas-systems_img_2.webp',
                   '/wasm_website/static/src/img/official_live_services/medical-gas-systems_img_3.webp',
                   '/wasm_website/static/src/img/official_live_services/medical-gas-systems_img_4.webp',
                   '/wasm_website/static/src/img/official_live_services/medical-gas-systems_img_5.webp',
                   '/wasm_website/static/src/img/official_live_services/medical-gas-systems_img_6.webp'],
  'slug': 'medical-gas-systems'},
 {'card_num': 7,
  'title_en': 'Alternative Energy Solutions',
  'title_ar': 'حلول الطاقة البديلة والشمسية',
  'subtitle_en': 'ARFA SPECIALIZED SYSTEMS implements sustainable renewable and alternative energy solutions designed to optimize power consumption, '
                 'reduce carbon footprint, and protect the environment.',
  'subtitle_ar': 'تطبق شركة عرفة للأنظمة المتخصصة حلول الطاقة التجددية والبديلة المستدامة لترشيد استهلاك الكهرباء وتقليل الأثر الكربونى.',
  'icon': 'fa-sun-o',
  'bg_img': '/wasm_website/static/src/img/official_live_services/alternative-energy-solutions_img_1.webp',
  'badge_en': 'Solar PV & Sustainable Energy',
  'badge_ar': 'الطاقة الشمسية والاستدامة البيئية',
  'features_en': ['Rooftop and ground-mounted commercial solar PV system design and installation.',
                  'Smart power consumption optimization reducing electrical utility expenditure.',
                  'Carbon footprint reduction and environmentally friendly infrastructure.',
                  'Grid-tied inverters and high-capacity battery energy storage setups (BESS).'],
  'features_ar': ['تصميم وتثبيت أنظمة الألواح الشمسية الكهروضوئية للمشروعات والمباني.',
                  'ترشيد استهلاك الكهرباء وخفض التكاليف التشغيلية للفواتير.',
                  'تقليل الانبعاثات الكربونية وحماية البيئة وفق معايير الاستدامة.',
                  'محولات الطاقة الهجينة وأنظمة بطاريات التخزين المستمرة.'],
  'gallery_imgs': ['/wasm_website/static/src/img/official_live_services/alternative-energy-solutions_img_1.webp',
                   '/wasm_website/static/src/img/official_live_services/alternative-energy-solutions_img_2.webp',
                   '/wasm_website/static/src/img/official_live_services/alternative-energy-solutions_img_3.webp',
                   '/wasm_website/static/src/img/official_live_services/alternative-energy-solutions_img_4.webp',
                   '/wasm_website/static/src/img/official_live_services/alternative-energy-solutions_img_5.webp',
                   '/wasm_website/static/src/img/official_live_services/alternative-energy-solutions_img_6.webp'],
  'slug': 'alternative-energy-solutions'},
 {'card_num': 8,
  'title_en': 'Infrastructure Development & Networks',
  'title_ar': 'البنية التحتية والشبكات',
  'subtitle_en': 'ARFA SPECIALIZED SYSTEMS delivers comprehensive infrastructure engineering solutions for wet and dry utility networks, power '
                 'distribution, district cooling, and stormwater management.',
  'subtitle_ar': 'تقدم شركة عرفة للأنظمة المتخصصة حلول هندسية متكاملة لشبكات البنية التحتية الجافة والمائية وتوزيع الكهرباء وتصريف السيول.',
  'icon': 'fa-road',
  'bg_img': '/wasm_website/static/src/img/official_live_services/infrastructure-development_img_1.webp',
  'badge_en': 'Heavy Utilities & Infrastructure Networks',
  'badge_ar': 'شبكات البنية التحتية الكبرى',
  'features_en': ['Constructing robust wet and dry utility networks for residential & commercial plots.',
                  'High-capacity electrical power distribution lines and district cooling pipelines.',
                  'Stormwater management, drainage networks, and site excavation & grading.',
                  'Advanced underground telecommunication pathways built for future expansion.'],
  'features_ar': ['إنشاء شبكات المرافق الجافة والمائية للمخططات السكنية والتجارية.',
                  'خطوط توزيع الكهرباء عالية السعة وأنابيب التبريد المركزي.',
                  'تصريف السيول ومياه الأمطار وأعمال الحفر وتسوية المواقع.',
                  'مسارات الاتصالات الأرضية وغرف التفتيش الجاهزة للتوسع المستقبلي.'],
  'gallery_imgs': ['/wasm_website/static/src/img/official_live_services/infrastructure-development_img_1.webp',
                   '/wasm_website/static/src/img/official_live_services/infrastructure-development_img_2.webp',
                   '/wasm_website/static/src/img/official_live_services/infrastructure-development_img_3.webp',
                   '/wasm_website/static/src/img/official_live_services/infrastructure-development_img_4.webp',
                   '/wasm_website/static/src/img/official_live_services/infrastructure-development_img_5.webp',
                   '/wasm_website/static/src/img/official_live_services/infrastructure-development_img_6.webp'],
  'slug': 'infrastructure-development'}]
