# -*- coding: utf-8 -*-
"""Texts + repeated items of: About (/about), Contact team (/contact-team),
Contact us (/contactus), Location (/location) and Our company (/our-company).

Rich paragraphs (about.story.p1, about.cta.text): words written between ** **
are shown highlighted in bold (same look as before), e.g. "since **1972**".
"""
PAGE = 'company'

_BOLD_HINT = ' (الكلمات بين ** ** تظهر بخط عريض مميز)'

TEXTS = [
    # ------------------------------------------------------------------ About
    ('about.hero.badge', 'الشارة أعلى البانر في صفحة من نحن', 'ARFA SPECIALIZED SYSTEMS', 'شركة عرفة للأنظمة المتخصصة'),
    ('about.hero.title', 'عنوان البانر في صفحة من نحن', 'ABOUT US', 'عن الشركة'),
    ('about.hero.subtitle', 'العنوان الفرعي في بانر صفحة من نحن',
     'Pioneering Engineering & Specialized Systems Since 1972', 'رواد الهندسة والأنظمة المتخصصة منذ عام 1972م'),
    ('about.story.badge', 'شارة قسم قصتنا', 'Our Legacy & Vision', 'إرثنا ورؤيتنا'),
    ('about.story.title', 'عنوان قسم قصتنا', 'ABOUT ARFA SPECIALIZED SYSTEMS', 'عن شركة عرفة للأنظمة المتخصصة'),
    ('about.story.p1', 'الفقرة الأولى في قسم قصتنا' + _BOLD_HINT,
     'Established on a visionary foundation dating back to **1972**, **ARFA SPECIALIZED SYSTEMS** was born with a clear '
     'mission — to bring national engineering excellence to global markets through innovation, quality, and '
     'sustainability in the construction and building sector.',
     'تأسست شركة عرفة للأنظمة المتخصصة على رؤية هندسية راسخة تمتد جذورها إلى عام **1972م**، وتأسست بمهمة واضحة — '
     'تقديم التميز الهندسي الوطني للأسواق العالمية من خلال الابتكار والجودة والاستدامة في قطاع البناء والتشييد.', True),
    ('about.story.intro', 'جملة التمهيد قبل المربع المميز في قسم قصتنا',
     'Over the decades, ARFA SPECIALIZED SYSTEMS has evolved into a multidisciplinary organization, comprising:',
     'عبر العقود الماضية، تطورت شركة عرفة للأنظمة المتخصصة لتصبح منظومة متكاملة متعددة التخصصات تشمل:', True),
    ('about.story.highlight', 'النص داخل المربع المميز (علامة صح) في قسم قصتنا',
     'ARFA Construction & Specialized Systems Company', 'شركة عرفة للمقاولات والأنظمة المتخصصة'),
    ('about.story.closing', 'السطر المائل في نهاية قسم قصتنا',
     'Delivered advanced engineering and energy solutions that redefine the future of smart construction.',
     'تقديم حلول هندسية وطاقة متقدمة تعيد تعريف مستقبل البناء الذكي والتصميم المستدام.', True),
    ('about.story.image_alt', 'وصف صورة قسم قصتنا (لمحركات البحث وقارئات الشاشة)',
     'ARFA Teamwork & Excellence', 'فريق عمل عرفة والتميز'),
    ('about.story.overlay_title', 'عنوان البطاقة فوق صورة قسم قصتنا', 'Synergy & Trust', 'التعاون والثقة'),
    ('about.story.overlay_subtitle', 'النص الصغير في البطاقة فوق الصورة',
     'Empowering teams, exceeding expectations', 'تمكين فرق العمل وتجاوز التوقعات'),
    ('about.expertise.badge', 'شارة قسم مجالات الخبرة', 'Core Competencies', 'القدرات الجوهرية'),
    ('about.expertise.title', 'عنوان قسم مجالات الخبرة', 'Our Areas of Expertise', 'مجالات خبراتنا وتخصصاتنا'),
    ('about.expertise.subtitle', 'الوصف تحت عنوان مجالات الخبرة',
     'Explore our specialized engineering capabilities across major industrial, commercial, and urban sectors.',
     'استكشف قدراتنا الهندسية المتخصصة عبر القطاعات الصناعية والتجارية والعمرانية الكبرى.', True),
    ('about.cta.text', 'نص الشريط الختامي الأزرق في صفحة من نحن' + _BOLD_HINT,
     'Driven by innovation and guided by decades of experience, **ARFA SPECIALIZED SYSTEMS** continues to build '
     'projects that reflect reliability, precision, and sustainability — shaping the future of smart construction '
     'and modern engineering in Saudi Arabia and beyond.',
     'مدفوعين بالابتكار ومسترشدين بعقود من الخبرة العريقة، تواصل شركة **عرفة للأنظمة المتخصصة** تنفيذ المشاريع '
     'التي تعكس الموثوقية والدقة والاستدامة — لصياغة مستقبل البناء الذكي والهندسة الحديثة في المملكة العربية '
     'السعودية وخارجها.', True),
    ('about.cta.button', 'زر الشريط الختامي (يفتح صفحة اتصل بنا)', 'Contact Our Team', 'تواصل مع فريقنا'),

    # ------------------------------------------------------- Contact team
    ('contact.team.hero.badge', 'الشارة أعلى البانر في صفحة التواصل مع الأقسام',
     'SPECIALIZED DEPARTMENTS', 'فريق العمل والأقسام المتخصصة'),
    ('contact.team.hero.title', 'عنوان البانر في صفحة التواصل مع الأقسام', 'CONTACT OUR TEAM', 'التواصل مع الأقسام'),
    ('contact.team.hero.subtitle', 'العنوان الفرعي في بانر صفحة التواصل مع الأقسام',
     'Direct Your Inquiry Directly to the Responsible Engineering Division',
     'تواصل مباشرة مع القسم الهندسي المعني بمشروعك'),

    # --------------------------------------------------------- Contact us
    ('contact.hero.badge', 'الشارة أعلى البانر في صفحة اتصل بنا', 'GET IN TOUCH', 'تواصل معنا'),
    ('contact.hero.title', 'عنوان البانر في صفحة اتصل بنا', 'CONTACT US', 'اتصل بنا'),
    ('contact.hero.subtitle', 'العنوان الفرعي في بانر صفحة اتصل بنا',
     'We are here to answer your technical and engineering inquiries',
     'نحن هنا للإجابة على جميع استفساراتكم الهندسية والفنية'),
    ('contact.card.phone_title', 'عنوان بطاقة الهاتف', 'Phone & WhatsApp', 'الهاتف والواتساب'),
    ('contact.card.whatsapp_btn', 'زر واتساب في بطاقة الهاتف', 'WhatsApp', 'واتساب'),
    ('contact.card.email_title', 'عنوان بطاقة البريد الإلكتروني', 'Email Address', 'البريد الإلكتروني'),
    ('contact.card.email_btn', 'زر إرسال بريد في بطاقة البريد', 'Send Email', 'أرسل بريداً'),
    ('contact.card.hours_title', 'عنوان بطاقة ساعات العمل', 'Working Hours', 'ساعات العمل'),
    ('contact.card.hours_off', 'سطر أيام الإجازة تحت ساعات العمل', 'Friday & Saturday: Off', 'الجمعة والسبت: إجازة'),
    ('contact.form.badge', 'شارة نموذج التواصل', 'Direct Inquiry & RFQ', 'نموذج التواصل المباشر'),
    ('contact.form.title', 'عنوان نموذج التواصل', 'Send Us a Direct Message', 'أرسل لنا استفسارك مباشرة'),
    ('contact.form.intro', 'الوصف تحت عنوان نموذج التواصل',
     'Fill out the form below to receive a response with a unique reference number via mail server.',
     'سيتم تسجيل طلبك فوراً وتزويدك وإرسال إشعار برقم مرجعي مميز عبر سيرفر البريد الإلكتروني.', True),
    ('contact.form.err_missing', 'رسالة خطأ: حقول مطلوبة فارغة',
     'Please fill in all required fields.', 'يرجى تعبئة جميع الحقول المطلوبة.'),
    ('contact.form.err_contact', 'رسالة خطأ: بريد أو جوال غير صحيح',
     'Please check the e-mail address and mobile number.', 'يرجى التأكد من البريد الإلكتروني ورقم الجوال.'),
    ('contact.form.err_rate', 'رسالة خطأ: طلبات كثيرة',
     'Too many requests were sent. Please try again in a few minutes.', 'تم إرسال طلبات كثيرة، يرجى المحاولة بعد دقائق.'),
    ('contact.form.err_generic', 'رسالة خطأ: تعذر الإرسال',
     'Your request could not be sent. Please try again.', 'تعذر إرسال الطلب، يرجى المحاولة مرة أخرى.'),
    ('contact.form.name_label', 'عنوان حقل الاسم', 'Full Name *', 'الاسم الكريم *'),
    ('contact.form.name_ph', 'النص الإرشادي داخل حقل الاسم', 'Enter your full name', 'أدخل اسمك الكريم'),
    ('contact.form.phone_label', 'عنوان حقل الجوال', 'Phone Number *', 'رقم الجوال *'),
    ('contact.form.phone_ph', 'النص الإرشادي داخل حقل الجوال', '05xxxxxxxx', '05xxxxxxxx'),
    ('contact.form.email_label', 'عنوان حقل البريد الإلكتروني', 'Email Address *', 'البريد الإلكتروني *'),
    ('contact.form.email_ph', 'النص الإرشادي داخل حقل البريد', 'name@domain.com', 'name@domain.com'),
    ('contact.form.location_label', 'عنوان حقل المدينة', 'City / Location *', 'المدينة / موقع المشروع *'),
    ('contact.form.location_ph', 'النص الإرشادي داخل حقل المدينة',
     'Riyadh / Jeddah / Eastern Province...', 'الرياض / جدة / الشرقية...'),
    ('contact.form.dept_label', 'عنوان قائمة القسم المختص', 'Target Department', 'القسم المختص'),
    ('contact.form.dept_sales', 'خيار القسم: المبيعات', 'Sales & Quotations', 'المبيعات وطلب الأسعار (Sales)'),
    ('contact.form.dept_engineering', 'خيار القسم: الهندسة', 'Engineering & Design', 'الهندسة والتصاميم (Engineering)'),
    ('contact.form.dept_projects', 'خيار القسم: إدارة المشاريع', 'Project Management', 'إدارة المشاريع (Projects)'),
    ('contact.form.dept_management', 'خيار القسم: الإدارة العامة', 'General Management', 'الإدارة العامة (Management)'),
    ('contact.form.type_label', 'عنوان قائمة نوع المشروع', 'Project Type', 'نوع المشروع'),
    ('contact.form.type_commercial', 'خيار نوع المشروع: تجاري', 'Commercial Project / Towers', 'مشروع تجاري / أبراج'),
    ('contact.form.type_residential', 'خيار نوع المشروع: سكني', 'Residential Compound / Villa', 'مجمع سكني / فيلا'),
    ('contact.form.type_industrial', 'خيار نوع المشروع: صناعي', 'Industrial Project / Warehouses', 'مشروع صناعي / مستودعات'),
    ('contact.form.type_infrastructure', 'خيار نوع المشروع: بنية تحتية',
     'Infrastructure & Electromechanical', 'بنية تحتية وكهروميكانيك'),
    ('contact.form.type_renovation', 'خيار نوع المشروع: ترميم', 'Renovation & Development', 'ترميم وتطوير'),
    ('contact.form.details_label', 'عنوان حقل تفاصيل الرسالة', 'Message / Project Details *', 'تفاصيل الاستفسار أو الرسالة *'),
    ('contact.form.details_ph', 'النص الإرشادي داخل حقل التفاصيل',
     'Write the details of your inquiry or request here...', 'اكتب تفاصيل استفسارك أو طلبك هنا...'),
    ('contact.form.submit', 'زر إرسال نموذج التواصل', 'Send Message Now', 'إرسال الرسالة والحصول على رقم مرجعي'),

    # ----------------------------------------------------------- Location
    ('location.hero.badge', 'الشارة أعلى البانر في صفحة موقعنا', 'OUR HEADQUARTERS', 'المقر الرئيسي'),
    ('location.hero.title', 'عنوان البانر في صفحة موقعنا (العنوان الفرعي = عنوان الشركة من الإعدادات)',
     'LOCATION', 'موقعنا الجغرافي'),
    ('location.map_title', 'وصف خريطة جوجل في صفحة موقعنا (لقارئات الشاشة)', 'Map of the ARFA head office location',
     'خريطة موقع المقر الرئيسي لشركة عرفة'),
    ('location.directions_btn', 'زر الاتجاهات تحت الخريطة', 'Get Directions', 'احصل على الاتجاهات'),

    # -------------------------------------------------------- Our company
    ('company.hero.badge', 'الشارة أعلى البانر في صفحة شركتنا',
     'ARFA GROUP & SISTER COMPANIES', 'مجموعة شركات عرفة والشركات التابعة'),
    ('company.hero.title', 'عنوان البانر في صفحة شركتنا', 'OUR GROUP & SISTER COMPANIES', 'شركتنا ومجموعتنا الهندسية'),
    ('company.hero.subtitle', 'العنوان الفرعي في بانر صفحة شركتنا',
     'ARFA SPECIALIZED SYSTEMS & Group Entities - Specialised Engineering, Contracting & Infrastructure Solutions',
     'شركة عرفة للأنظمة المتخصصة والشركات الشقيقة - ريادة هندسية وتكامل في المقاولات العامة والبنية التحتية'),
    ('company.divisions.badge', 'شارة قسم شركات المجموعة', 'Group Capabilities & Divisions', 'قدرات المجموعة وأقسامها'),
    ('company.divisions.title', 'عنوان قسم شركات المجموعة', 'OUR GROUP & SISTER COMPANIES', 'مجموعتنا والشركات الشقيقة'),
    ('company.hq.badge', 'شارة بطاقة المقر الرئيسي', 'HEAD OFFICE', 'المقر الرئيسي'),
    ('company.hq.name', 'اسم الشركة في بطاقة المقر الرئيسي', 'ARFA SPECIALIZED SYSTEMS', 'شركة عرفة للأنظمة المتخصصة'),
    ('company.hq.building', 'اسم المبنى (السطر الذهبي) في بطاقة المقر الرئيسي',
     'Gulf Center Kaki (مركز الخليج كعكي)', 'مركز الخليج كعكي'),
    ('company.hq.address1', 'عنوان المقر الرئيسي - السطر الأول (الشارع والحي)',
     '7947 Abu Bakr Al Siddiq Road, Al Sharafeyah District', '7947 طريق أبو بكر الصديق، حي الشرفية'),
    ('company.hq.address2', 'عنوان المقر الرئيسي - السطر الثاني (المدينة والدولة)',
     'Jeddah 23218, Kingdom of Saudi Arabia', 'جدة 23218، المملكة العربية السعودية'),
    ('company.hq.map_title', 'وصف خريطة المقر الرئيسي في صفحة شركتنا (لقارئات الشاشة)',
     'Map of the ARFA head office location', 'خريطة موقع المقر الرئيسي لشركة عرفة'),
    ('company.hq.directions_btn', 'زر الاتجاهات في بطاقة المقر الرئيسي',
     'Get Directions on Google Maps', 'احصل على الاتجاهات عبر خرائط جوجل'),
]

ITEMS = [
    # ------------------------------------------- About: areas of expertise
    {'section': 'expertise', 'icon': 'fa-cubes',
     'title_en': 'Modern Building Systems', 'title_ar': 'الأنظمة الحديثة للبناء والتطوير المعماري'},
    {'section': 'expertise', 'icon': 'fa-cogs',
     'title_en': 'Electromechanical Systems (HVAC, Plumbing, Fire Fighting, Electrical Works)',
     'title_ar': 'الأنظمة الإلكتروميكانيكية (التكييف، السباكة، مكافحة الحريق، الكهرباء)'},
    {'section': 'expertise', 'icon': 'fa-leaf',
     'title_en': 'Alternative & Renewable Energy Solutions', 'title_ar': 'حلول الطاقة البديلة والمتجددة والاستدامة'},
    {'section': 'expertise', 'icon': 'fa-microchip',
     'title_en': 'Smart Building Automation and IoT Systems', 'title_ar': 'أتمتة المباني الذكية وأنظمة إنترنت الأشياء (IoT)'},
    {'section': 'expertise', 'icon': 'fa-shield',
     'title_en': 'Fire Protection & Prevention Systems (NFPA / UL / FM Standards)',
     'title_ar': 'أنظمة الحماية ومكافحة الحريق (وفق معايير NFPA / UL / FM)'},
    {'section': 'expertise', 'icon': 'fa-user-md',
     'title_en': 'Medical Gas Networks and Central Supply Systems',
     'title_ar': 'شبكات الغازات الطبية وأنظمة الإمداد المركزي للمستشفيات'},
    {'section': 'expertise', 'icon': 'fa-road',
     'title_en': 'Infrastructure for Residential and Industrial Cities', 'title_ar': 'تطوير البنية التحتية للمدن السكنية والصناعية'},
    {'section': 'expertise', 'icon': 'fa-building-o',
     'title_en': 'Design and Construction of Residential, Urban, Resort, and Industrial Buildings',
     'title_ar': 'تصميم وإنشاء المباني السكنية والعمرانية والمجمعات الصناعية'},
    {'section': 'expertise', 'icon': 'fa-truck',
     'title_en': 'Electromechanical Equipment Supplies', 'title_ar': 'توريد وتحديث المعدات والتجهيزات الإلكتروميكانيكية'},
    {'section': 'expertise', 'icon': 'fa-hospital-o',
     'title_en': 'Construction & Maintenance of Hospitals and Health Facilities',
     'title_ar': 'إنشاء وصيانة المستشفيات والمراكز الصحية المتخصصة'},
    {'section': 'expertise', 'icon': 'fa-industry',
     'title_en': 'Industrial Factories and Metal Structures', 'title_ar': 'إنشاء المصانع والهياكل والإنشاءات المعدنية'},
    {'section': 'expertise', 'icon': 'fa-shopping-cart',
     'title_en': 'Development of Commercial Complexes and Markets', 'title_ar': 'تطوير وتجهيز المجمعات والأسواق التجارية الكبرى'},

    # ------------------------------------- Contact: department cards
    {'section': 'department', 'icon': 'fa-pencil-square-o',
     'title_en': 'Sales Department', 'title_ar': 'قسم المبيعات',
     'desc_en': 'RFQs, estimating, and commercial proposals.',
     'desc_ar': 'طلبات عروض الأسعار والتسعير والعروض التجارية.',
     'link_url': '/quote?dept=sales', 'link_label_en': 'Contact Sales', 'link_label_ar': 'تواصل مع المبيعات'},
    {'section': 'department', 'icon': 'fa-cogs',
     'title_en': 'Engineering Department', 'title_ar': 'القسم الهندسي',
     'desc_en': 'Architectural drawings, MEP specs, and SBC compliance.',
     'desc_ar': 'المخططات المعمارية ومواصفات الأعمال الكهروميكانيكية والالتزام بكود البناء السعودي.',
     'link_url': '/quote?dept=engineering', 'link_label_en': 'Contact Engineering', 'link_label_ar': 'تواصل مع الهندسة'},
    {'section': 'department', 'icon': 'fa-building',
     'title_en': 'Project Management', 'title_ar': 'إدارة المشاريع',
     'desc_en': 'Schedules, milestones, site execution, and progress.',
     'desc_ar': 'الجداول الزمنية والمراحل الرئيسية والتنفيذ في الموقع ومتابعة التقدم.',
     'link_url': '/quote?dept=projects', 'link_label_en': 'Contact Projects', 'link_label_ar': 'تواصل مع إدارة المشاريع'},

    # ---------------------------------- Our company: group divisions
    {'section': 'division', 'icon': 'fa-cogs',
     'title_en': 'ARFA SPECIALIZED SYSTEMS', 'title_ar': 'شركة عرفة للأنظمة المتخصصة',
     'desc_en': 'Comprehensive Electro-Mechanical (MEP), Medical Gas Pipeline Systems (MGPS), Fire Safety & Civil Protection.',
     'desc_ar': 'أعمال كهروميكانيكية شاملة (MEP)، وأنظمة شبكات الغازات الطبية (MGPS)، والسلامة من الحريق والحماية المدنية.'},
    {'section': 'division', 'icon': 'fa-building',
     'title_en': 'Gulf Center Kaki Division', 'title_ar': 'قسم مركز الخليج كعكي',
     'desc_en': 'Headquarters & Commercial Executive Division leading technical project engineering, management & client relations.',
     'desc_ar': 'المقر الرئيسي والقسم التنفيذي التجاري الذي يقود الهندسة الفنية للمشاريع وإدارتها والعلاقات مع العملاء.'},
    {'section': 'division', 'icon': 'fa-cubes',
     'title_en': 'Modern Building Systems', 'title_ar': 'أنظمة البناء الحديثة',
     'desc_en': 'Prefabricated steel structures, SBC-compliant concrete framing, modern glass facades & turnkey interiors.',
     'desc_ar': 'الهياكل الفولاذية سابقة التجهيز، والهياكل الخرسانية المطابقة لكود البناء السعودي، والواجهات الزجاجية الحديثة، والتشطيبات الداخلية المتكاملة.'},
    {'section': 'division', 'icon': 'fa-bolt',
     'title_en': 'Energy & Infrastructure', 'title_ar': 'الطاقة والبنية التحتية',
     'desc_en': 'Alternative renewable solar energy systems, smart grid integration & wet/dry utility infrastructure developments.',
     'desc_ar': 'أنظمة الطاقة الشمسية المتجددة البديلة، وتكامل الشبكات الذكية، وتطوير شبكات المرافق الرطبة والجافة.'},
]
