# -*- coding: utf-8 -*-
PAGE = 'home'

TEXTS = [
    # --- Hero banner ---
    ('home.page_title', 'عنوان تبويب المتصفح للصفحة الرئيسية (احتياطي إذا لم يُحدد عنوان SEO)',
     'ARFA SPECIALIZED SYSTEMS - Official Website', 'عرفة للأنظمة المتخصصة - الموقع الرسمي'),
    ('home.hero.title', 'العنوان الرئيسي الكبير في البانر', 'ARFA SPECIALIZED SYSTEMS', 'عرفة للأنظمة المتخصصة'),
    ('home.hero.lead', 'النص المتحرك (الآلة الكاتبة) تحت عنوان البانر',
     'ARFA Specialized Systems is your premier partner in engineering and construction, delivering advanced '
     'building technologies and leading-edge energy solutions.',
     'شركة عرفة للأنظمة المتخصصة هي شريكك الهندسي والإنشائي الأول، حيث تقدم أحدث تقنيات البناء وحلول '
     'الكهروميكانيك والمباني الذكية.'),
    ('home.hero.btn_quote', 'زر طلب عرض السعر في البانر', 'Request a Quote', 'اطلب عرض سعر'),
    ('home.hero.btn_profile', 'زر ملف الشركة في البانر', 'Company Profile', 'ملف الشركة'),
    ('home.hero.btn_contact', 'زر تواصل معنا في البانر', 'Contact Us', 'تواصل معنا'),
    # --- Corporate video showcase ---
    ('home.showcase.btn_quote', 'زر طلب عرض السعر في قسم الفيديو', 'Request Quote', 'اطلب عرض سعر'),
    ('home.showcase.btn_more', 'زر اعرف المزيد في قسم الفيديو (قديم، استُبدل بالنص التالي)', 'Learn More', 'اعرف المزيد'),
    ('home.showcase.btn_more_about', 'زر "اعرف المزيد عنا" في قسم الفيديو (نص وصفي للرابط إلى صفحة من نحن)',
     'Learn More About Us', 'اعرف المزيد عنا'),
    ('home.showcase.video_fallback', 'رسالة تظهر إذا كان المتصفح لا يدعم الفيديو',
     'Your browser does not support the video tag.', 'متصفحك لا يدعم تشغيل الفيديو.'),
    ('home.showcase.play_label', 'وصف زر تشغيل الفيديو (لقارئات الشاشة)', 'Play Video', 'تشغيل الفيديو'),
    # --- Why choose us ---
    ('home.why.title', 'عنوان قسم لماذا تختارنا', 'Why Choose ARFA SPECIALIZED SYSTEMS?',
     'لماذا تختار عرفة للأنظمة المتخصصة؟'),
    ('home.why.subtitle', 'النص تحت عنوان قسم لماذا تختارنا',
     'We deliver structural excellence backed by certified engineering standards and rigid deadlines.',
     'نقدم التميز الإنشائي المدعوم بمعايير هندسية معتمدة والتزام صارم بالمواعيد.'),
    # --- Services slider ---
    ('home.services.title', 'عنوان قسم الخدمات', 'Our Engineering & Construction Services',
     'خدماتنا الهندسية والإنشائية'),
    ('home.services.subtitle', 'النص تحت عنوان قسم الخدمات',
     'Comprehensive contracting solutions meeting all Saudi construction standards',
     'حلول مقاولات متكاملة تلبي جميع معايير البناء السعودية'),
    ('home.services.btn_details', 'زر التفاصيل في كروت الخدمات', 'Details', 'التفاصيل'),
    ('home.services.btn_request', 'زر طلب الخدمة في كروت الخدمات', 'Request Service', 'اطلب الخدمة'),
    # --- Featured projects ---
    ('home.projects.title', 'عنوان قسم المشاريع المميزة', 'Featured Projects', 'مشاريع مميزة'),
    ('home.projects.subtitle', 'النص تحت عنوان قسم المشاريع المميزة',
     'Samples of our major structural and commercial development portfolio',
     'نماذج من أبرز مشاريعنا الإنشائية والتجارية'),
    ('home.projects.btn_all', 'زر عرض كل المشاريع (أعلى القسم)', 'View All Projects', 'عرض كل المشاريع'),
    ('home.projects.state_completed', 'شارة حالة المشروع: مكتمل', 'Completed', 'مكتمل بنجاح'),
    ('home.projects.state_in_progress', 'شارة حالة المشروع: تحت التنفيذ', 'In Progress', 'تحت التنفيذ'),
    ('home.projects.btn_details', 'زر التفاصيل في كروت المشاريع', 'Details', 'التفاصيل'),
    ('home.projects.btn_all_page', 'زر صفحة كل المشاريع (أسفل القسم)', 'View All Projects Page',
     'الانتقال إلى صفحة كل المشاريع'),
    # --- Testimonials / team / partners ---
    ('home.testimonials.title', 'عنوان قسم آراء العملاء', 'What Our Clients Say', 'ماذا يقول عملاؤنا'),
    ('home.team.title', 'عنوان قسم فريق العمل', 'OUR TEAM', 'فريق العمل'),
    ('home.partners.title', 'عنوان قسم الشركاء', 'OUR PARTNERS', 'شركاؤنا'),
    ('home.partners.visit', 'شارة زيارة الموقع في كروت الشركاء', 'Visit Website', 'زيارة الموقع'),
]

# Team members of the homepage (title = name, subtitle = role, desc = bio, badge = bottom badge).
ITEMS = [
    {'section': 'team',
     'title_en': 'CEO MAHMOUD RASHWAN', 'title_ar': 'محمود رشوان',
     'subtitle_en': 'Chief Executive Officer', 'subtitle_ar': 'الرئيس التنفيذي',
     'desc_en': 'Chief Executive Officer leading strategic growth, corporate governance, and engineering excellence across Saudi Arabia.',
     'desc_ar': 'الرئيس التنفيذي الذي يقود النمو الاستراتيجي والحوكمة المؤسسية والتميز الهندسي في جميع أنحاء المملكة العربية السعودية.',
     'badge_en': 'Executive Leader', 'badge_ar': 'القيادة التنفيذية',
     'icon': 'fa-briefcase',
     'image_url': 'https://arfa-sa.com/web/image/1615-a832121c/Man_posing_in_executive_suit_202608092321.svg'},
    {'section': 'team',
     'title_en': 'Ahmed El-Ganzoury', 'title_ar': 'أحمد الجنزوري',
     'subtitle_en': 'MEP Project Engineer & Coordinator', 'subtitle_ar': 'مهندس ومنسق مشاريع الأنظمة الكهروميكانيكية',
     'desc_en': 'Expert in mechanical, electrical, and plumbing engineering coordination and complex project delivery.',
     'desc_ar': 'خبير في تنسيق الأعمال الميكانيكية والكهربائية والصحية وتسليم المشاريع المعقدة.',
     'badge_en': 'MEP Coordinator', 'badge_ar': 'منسق الأنظمة الكهروميكانيكية',
     'icon': 'fa-cogs',
     'image_url': 'https://arfa-sa.com/web/image/1646-d576ddf0/Man_in_business_suit_2K_202608092341.svg'},
    {'section': 'team',
     'title_en': 'Mohamed El-Nashar', 'title_ar': 'محمد النشار',
     'subtitle_en': 'Mechanical Engineer', 'subtitle_ar': 'مهندس ميكانيكا',
     'desc_en': 'Specialized in HVAC systems, fire fighting networks, and mechanical infrastructure design.',
     'desc_ar': 'متخصص في أنظمة التكييف والتهوية وشبكات مكافحة الحريق وتصميم البنية التحتية الميكانيكية.',
     'badge_en': 'Mechanical Specialist', 'badge_ar': 'أخصائي ميكانيكا',
     'icon': 'fa-wrench',
     'image_url': 'https://arfa-sa.com/web/image/1647-b6230cf8/Man_wearing_suit_portrait_2K_202608092345.svg'},
    {'section': 'team',
     'title_en': 'Mohamed Shaaban', 'title_ar': 'محمد شعبان',
     'subtitle_en': 'Sales Engineer', 'subtitle_ar': 'مهندس مبيعات',
     'desc_en': 'Bridging engineering solutions with client requirements and technical project proposals.',
     'desc_ar': 'يربط الحلول الهندسية باحتياجات العملاء ويعد العروض الفنية للمشاريع.',
     'badge_en': 'Sales Engineer', 'badge_ar': 'مهندس مبيعات',
     'icon': 'fa-handshake-o',
     'image_url': 'https://arfa-sa.com/web/image/1649-fe1dac8c/Man_wearing_business_suit_portrait_202608100004.svg'},
    {'section': 'team',
     'title_en': 'Waleed Saken', 'title_ar': 'وليد ساكن',
     'subtitle_en': 'Sales Manager', 'subtitle_ar': 'مدير المبيعات',
     'desc_en': 'Directing commercial strategy, client relationships, and business development operations.',
     'desc_ar': 'يدير الاستراتيجية التجارية وعلاقات العملاء وعمليات تطوير الأعمال.',
     'badge_en': 'Sales Manager', 'badge_ar': 'مدير المبيعات',
     'icon': 'fa-line-chart',
     'image_url': 'https://arfa-sa.com/web/image/1621-fd7d5dea/Man_smiling_in_corporate_portrait_202608092357.svg'},
    {'section': 'team',
     'title_en': 'Ahmed Rashwan', 'title_ar': 'أحمد رشوان',
     'subtitle_en': 'Sales Specialist', 'subtitle_ar': 'أخصائي مبيعات',
     'desc_en': 'Managing client consultations, estimation analysis, and contract execution.',
     'desc_ar': 'يتولى استشارات العملاء وتحليل التسعير ومتابعة تنفيذ العقود.',
     'badge_en': 'Sales Specialist', 'badge_ar': 'أخصائي مبيعات',
     'icon': 'fa-user-circle',
     'image_url': 'https://arfa-sa.com/web/image/1650-c303736b/Man_wearing_business_suit_2K_202608092329.svg'},
    {'section': 'team',
     'title_en': 'Mahmoud Al-Asaad', 'title_ar': 'محمود الأسعد',
     'subtitle_en': 'Electrical Engineer', 'subtitle_ar': 'مهندس كهرباء',
     'desc_en': 'Power distribution, smart building control, low-current systems, and renewable integration.',
     'desc_ar': 'توزيع الطاقة الكهربائية، وأنظمة التحكم في المباني الذكية، وأنظمة التيار المنخفض، ودمج الطاقة المتجددة.',
     'badge_en': 'Electrical Engineer', 'badge_ar': 'مهندس كهرباء',
     'icon': 'fa-bolt',
     'image_url': 'https://arfa-sa.com/web/image/1645-8de7a639/Electrical_engineer_corporate_he%25E2%2580%25A6_2K_202608092334.svg'},
    {'section': 'team',
     'title_en': 'Mohamed Nagah', 'title_ar': 'محمد نجاح',
     'subtitle_en': 'Civil Engineer', 'subtitle_ar': 'مهندس مدني',
     'desc_en': 'Structural analysis, site supervision, concrete technology, and project execution according to SBC.',
     'desc_ar': 'التحليل الإنشائي، والإشراف على المواقع، وتقنيات الخرسانة، وتنفيذ المشاريع وفق كود البناء السعودي.',
     'badge_en': 'Civil Engineer', 'badge_ar': 'مهندس مدني',
     'icon': 'fa-building',
     'image_url': 'https://arfa-sa.com/web/image/1651-1ff72528/Man_wearing_business_suit_2K_202608111748.svg'},
]
