# -*- coding: utf-8 -*-
"""Texts of the services page, the service pages, the projects page and the project page."""
PAGE = 'projects'

TEXTS = [
    # ---------------- /services ----------------
    ('services.page_title', 'عنوان تبويب المتصفح لصفحة الخدمات',
     'Our Services | ARFA SPECIALIZED SYSTEMS', 'خدماتنا المتخصصة | شركة عرفة للأنظمة المتخصصة'),
    ('services.hero.badge', 'الشارة أعلى بانر صفحة الخدمات',
     'ENGINEERING & CONSTRUCTION SERVICES', 'خدمات الهندسة والمقاولات المتخصصة'),
    ('services.hero.title', 'العنوان الرئيسي في بانر صفحة الخدمات', 'OUR SERVICES', 'خدماتنا المتخصصة'),
    ('services.hero.subtitle', 'النص تحت العنوان في بانر صفحة الخدمات',
     'Explore Our Complete Scope of Contracting & Technical Solutions',
     'استكشف نطاق خدماتنا الشامل في المقاولات العامة والحلول التخصصية'),
    ('services.card.quote_btn', 'زر طلب عرض السعر في كرت كل خدمة', 'Request a Quote', 'اطلب عرض سعر'),

    # ---------------- service page (one per service) ----------------
    ('service_detail.title_suffix', 'ما يُضاف بعد اسم الخدمة في عنوان تبويب المتصفح',
     'ARFA SPECIALIZED SYSTEMS', 'شركة عرفة للأنظمة المتخصصة'),
    ('service_detail.banner_alt', 'وصف صورة البانر لقارئات الشاشة', 'Service Banner', 'صورة الخدمة'),
    ('service_detail.overview.title', 'عنوان قسم النظرة العامة بجوار صورة الخدمة',
     'Overview & Capabilities', 'نظرة عامة والقدرات'),
    ('service_detail.btn.start', 'زر بدء مشروع (يفتح طلب عرض السعر للخدمة)', 'Start Service Project', 'ابدأ مشروعك معنا'),
    ('service_detail.btn.contact', 'زر التواصل مع الفريق الهندسي', 'Contact Engineering Team', 'تواصل مع الفريق الهندسي'),
    ('service_detail.gallery.badge', 'الشارة أعلى معرض صور الخدمة', 'Project & Site Showcase', 'من مشاريعنا ومواقعنا'),
    ('service_detail.gallery.title', 'عنوان معرض صور الخدمة', 'Official Service Gallery', 'معرض صور الخدمة'),
    ('service_detail.gallery.text', 'النص تحت عنوان معرض صور الخدمة',
     'Real site execution photos, equipment installations, and project milestones for this division.',
     'صور حقيقية من مواقع التنفيذ وتركيب المعدات ومراحل إنجاز المشاريع في هذا القسم.'),
    ('service_detail.gallery.img_alt', 'وصف صور معرض الخدمة لقارئات الشاشة',
     'Official Service Gallery Photo', 'صورة من معرض الخدمة'),
    ('service_detail.other.title', 'عنوان قائمة الخدمات الأخرى أسفل الصفحة',
     'Explore Other ARFA Engineering Services', 'استكشف خدمات عرفة الهندسية الأخرى'),

    # ---------------- /projects ----------------
    ('projects.page_title', 'عنوان تبويب المتصفح لصفحة المشاريع',
     'Our Projects | ARFA SPECIALIZED SYSTEMS', 'مشاريعنا | شركة عرفة للأنظمة المتخصصة'),
    ('projects.hero.badge', 'الشارة أعلى بانر صفحة المشاريع', 'PROJECTS PORTFOLIO & MILESTONES', 'معرض المشاريع والإنجازات'),
    ('projects.hero.title', 'العنوان الرئيسي في بانر صفحة المشاريع', 'OUR PROJECTS', 'مشاريعنا'),
    ('projects.hero.subtitle', 'النص تحت العنوان في بانر صفحة المشاريع',
     'Highlighting Commercial, Residential & Infrastructure Milestones',
     'نستعرض أبرز مشاريعنا في القطاعات التجارية والسكنية والبنية التحتية'),
    ('projects.filter.all', 'زر التصفية: جميع المشاريع', 'All Projects', 'جميع المشاريع'),
    ('projects.filter.completed', 'زر التصفية: المشاريع المكتملة', 'Completed', 'مكتملة'),
    ('projects.filter.in_progress', 'زر التصفية: المشاريع قيد التنفيذ', 'In Progress', 'قيد التنفيذ'),
    ('projects.profile_btn', 'زر تحميل بروفايل الشركة', 'Company Profile (PDF)', 'بروفايل الشركة (PDF)'),
    ('projects.card.img_alt', 'وصف صورة كرت المشروع لقارئات الشاشة', 'Project Image', 'صورة المشروع'),
    ('projects.state.completed', 'حالة المشروع: مكتمل (في الكروت وصفحة المشروع)', 'Completed', 'مكتمل بنجاح'),
    ('projects.state.in_progress', 'حالة المشروع: تحت التنفيذ (في الكروت وصفحة المشروع)', 'In Progress', 'تحت التنفيذ'),
    ('projects.type.commercial', 'نوع المشروع: تجاري', 'Commercial & Towers', 'أبراج ومشاريع تجارية'),
    ('projects.type.residential', 'نوع المشروع: سكني', 'Residential', 'مجمعات سكنية وفلل'),
    ('projects.type.mep', 'نوع المشروع: كهروميكانيك', 'MEP & HVAC', 'أعمال كهروميكانيكية وتكييف'),
    ('projects.type.infrastructure', 'نوع المشروع: بنية تحتية', 'Structure & Infrastructure', 'بناء عظم وبنية تحتية'),
    ('projects.card.area', 'كلمة "المساحة" أسفل كرت المشروع', 'Area:', 'المساحة:'),
    ('projects.card.na', 'ما يظهر عند عدم إدخال المساحة', 'N/A', 'غير محدد'),
    ('projects.card.area_unit', 'وحدة المساحة في كرت المشروع', 'm²', 'م²'),
    ('projects.card.client_fallback', 'ما يظهر مكان اسم المالك إذا لم يُدخل', 'Commercial', 'تجاري'),
    ('projects.gallery.badge', 'الشارة أعلى شريط معرض الصور', 'Official Media & Field Execution', 'الوسائط الرسمية والتنفيذ الميداني'),
    ('projects.gallery.title', 'عنوان شريط معرض الصور', 'PHOTO GALLERY', 'معرض الصور'),
    ('projects.gallery.text', 'النص تحت عنوان معرض الصور',
     'Explore real site execution photos, equipment installations, and project milestones for ARFA specialized engineering divisions.',
     'استكشف صوراً حقيقية من مواقع التنفيذ وتركيب المعدات ومراحل إنجاز المشاريع لأقسام عرفة الهندسية المتخصصة.'),
    ('projects.gallery.img_alt', 'وصف صور شريط المعرض لقارئات الشاشة', 'ARFA Project Gallery Photo', 'صورة من معرض مشاريع عرفة'),
    ('projects.video.play', 'وصف زر تشغيل الفيديو في المعارض', 'Play video', 'تشغيل الفيديو'),
    ('projects.lightbox.close', 'زر إغلاق عارض الصور والفيديو', 'Close', 'إغلاق'),
    ('projects.lightbox.prev', 'زر السابق في عارض الصور والفيديو', 'Previous', 'السابق'),
    ('projects.lightbox.next', 'زر التالي في عارض الصور والفيديو', 'Next', 'التالي'),

    # ---------------- /projects/<id> ----------------
    ('project_detail.title_suffix', 'ما يُضاف بعد اسم المشروع في عنوان تبويب المتصفح',
     'ARFA SPECIALIZED SYSTEMS', 'شركة عرفة للأنظمة المتخصصة'),
    ('project_detail.crumb.aria', 'وصف شريط المسار لقارئات الشاشة', 'Breadcrumb', 'مسار التنقل'),
    ('project_detail.crumb.home', 'شريط المسار: الرئيسية', 'Home', 'الرئيسية'),
    ('project_detail.crumb.projects', 'شريط المسار: المشاريع', 'Projects', 'المشاريع'),
    ('project_detail.location_aria', 'وصف أيقونة الموقع لقارئات الشاشة', 'Location', 'الموقع'),
    ('project_detail.facts.aria', 'وصف بطاقة بيانات المشروع لقارئات الشاشة', 'Project facts', 'بيانات المشروع'),
    ('project_detail.facts.title', 'عنوان بطاقة بيانات المشروع', 'Project at a glance', 'المشروع في لمحة'),
    ('project_detail.facts.role', 'بطاقة البيانات: دور عرفة', 'Our role', 'دور عرفة'),
    ('project_detail.facts.client', 'بطاقة البيانات: المالك', 'Client', 'المالك'),
    ('project_detail.facts.brand', 'بطاقة البيانات: العلامة / المشغّل', 'Brand / Operator', 'العلامة / المشغّل'),
    ('project_detail.facts.location', 'بطاقة البيانات: الموقع', 'Location', 'الموقع'),
    ('project_detail.facts.build', 'بطاقة البيانات: تكوين المبنى', 'Build', 'تكوين المبنى'),
    ('project_detail.facts.units', 'بطاقة البيانات: الوحدات / الغرف', 'Units / Keys', 'الوحدات / الغرف'),
    ('project_detail.facts.area', 'بطاقة البيانات: المساحة المنفذة', 'Executed area', 'المساحة المنفذة'),
    ('project_detail.area_unit', 'وحدة المساحة في صفحة المشروع', 'm²', 'م²'),
    ('project_detail.facts.facilities', 'بطاقة البيانات: المرافق', 'Facilities', 'المرافق'),
    ('project_detail.facts.completion', 'بطاقة البيانات: تاريخ التسليم', 'Completion', 'تاريخ التسليم'),
    ('project_detail.facts.cta', 'زر أسفل بطاقة البيانات (يفتح طلب عرض السعر)', 'Discuss a similar project', 'ناقشنا في مشروع مماثل'),
    ('project_detail.acc.general', 'عنوان القسم القابل للطي: معلومات المبنى', 'General building information', 'معلومات عامة عن المبنى'),
    ('project_detail.row.address', 'معلومات المبنى: العنوان', 'Project address', 'عنوان المشروع'),
    ('project_detail.row.building_type', 'معلومات المبنى: نوع المبنى', 'Building type', 'نوع المبنى'),
    ('project_detail.row.category', 'معلومات المبنى: التصنيف', 'Category', 'التصنيف'),
    ('project_detail.acc.description', 'عنوان القسم القابل للطي: وصف المشروع', 'Project description', 'وصف المشروع'),
    ('project_detail.description.fallback', 'جملة تظهر إذا لم يُكتب وصف للمشروع',
     'Executed by ARFA in line with the Saudi Building Code.', 'نُفّذ بواسطة عرفة وفق كود البناء السعودي.'),
    ('project_detail.acc.scope', 'عنوان القسم القابل للطي: نطاق العمل', 'Scope of work & deliverables', 'نطاق العمل والمخرجات'),
    ('project_detail.row.status', 'نطاق العمل: الحالة (إذا لم تُدخل تفاصيل)', 'Status', 'الحالة'),
    ('project_detail.gallery.title', 'عنوان معرض صور المشروع', 'Project gallery', 'معرض صور المشروع'),
    ('project_detail.gallery.all', 'زر التصفية "الكل" في معرض المشروع', 'All', 'الكل'),
    ('project_detail.more.title', 'عنوان قسم الصور الإضافية من المشاريع', 'More from our projects', 'صور إضافية من مشاريعنا'),
    ('project_detail.more.subtitle', 'النص تحت عنوان الصور الإضافية',
     'A wider look at sites delivered by ARFA across the Kingdom.', 'نظرة أوسع على مواقع نفذتها عرفة في أنحاء المملكة.'),
    ('project_detail.more.all', 'رابط كل المشاريع (في الصور الإضافية وأسفل الصفحة)', 'All projects', 'كل المشاريع'),
    ('project_detail.more.img_alt', 'وصف الصور الإضافية لقارئات الشاشة (إذا لم يكن لها عنوان)', 'ARFA project photo', 'صورة من مشاريع عرفة'),
    ('project_detail.pager.aria', 'وصف شريط التنقل بين المشاريع لقارئات الشاشة', 'Projects', 'المشاريع'),
    ('project_detail.pager.prev', 'رابط المشروع السابق', 'Previous project', 'المشروع السابق'),
    ('project_detail.pager.next', 'رابط المشروع التالي', 'Next project', 'المشروع التالي'),
]

ITEMS = [
]
