# -*- coding: utf-8 -*-
"""Page names and descriptions for Google / social sharing (the <title> and meta description)."""
PAGE = 'seo'

TEXTS = [('seo.home.title', 'اسم الصفحة في عنوان جوجل: /', 'Saudi Contractor Since 1972', 'مقاولات وأنظمة متخصصة منذ 1972'),
 ('seo.about.title', 'اسم الصفحة في عنوان جوجل: /about', 'About Us', 'عن الشركة'),
 ('seo.about.desc',
  'وصف الصفحة في جوجل: /about',
  'ARFA Construction & Specialized Systems: a Saudi contractor since 1972 delivering structural, MEP, smart-building, fire-protection and '
  'medical-gas projects across the Kingdom.',
  'شركة عرفة للأنظمة المتخصصة: مقاول سعودي منذ عام 1972 ينفذ أعمال الإنشاءات والكهروميكانيك والمباني الذكية والحماية من الحريق والغازات الطبية في '
  'أنحاء المملكة.',
  True),
 ('seo.our_company.title', 'اسم الصفحة في عنوان جوجل: /our-company', 'Our Company', 'شركتنا'),
 ('seo.our_company.desc',
  'وصف الصفحة في جوجل: /our-company',
  'Company divisions, leadership and certifications of ARFA Construction & Specialized Systems in Saudi Arabia.',
  'أقسام شركة عرفة للأنظمة المتخصصة وفريق القيادة والاعتمادات في المملكة العربية السعودية.',
  True),
 ('seo.services.title', 'اسم الصفحة في عنوان جوجل: /services', 'Our Services', 'خدماتنا'),
 ('seo.services.desc',
  'وصف الصفحة في جوجل: /services',
  'Planning & construction, MEP, smart building (BMS), modern building systems, fire protection, medical gas, solar energy and infrastructure works '
  'by ARFA.',
  'التخطيط والإنشاءات، الكهروميكانيك، المباني الذكية، الأنظمة الحديثة، الحماية من الحريق، الغازات الطبية، الطاقة الشمسية والبنية التحتية من شركة '
  'عرفة.',
  True),
 ('seo.projects.title', 'اسم الصفحة في عنوان جوجل: /projects', 'Our Projects', 'مشاريعنا'),
 ('seo.projects.desc',
  'وصف الصفحة في جوجل: /projects',
  'Completed and ongoing hotel, residential, healthcare and commercial projects delivered by ARFA Construction & Specialized Systems.',
  'مشاريع شركة عرفة للأنظمة المتخصصة المنجزة والجارية: فنادق ومبانٍ سكنية وصحية وتجارية.',
  True),
 ('seo.news.title', 'اسم الصفحة في عنوان جوجل: /news', 'News & Media', 'الأخبار والأنشطة'),
 ('seo.news.desc',
  'وصف الصفحة في جوجل: /news',
  'Latest news, project milestones and events from ARFA Construction & Specialized Systems.',
  'آخر أخبار شركة عرفة للأنظمة المتخصصة ومراحل المشاريع والفعاليات.',
  True),
 ('seo.quote.title', 'اسم الصفحة في عنوان جوجل: /quote', 'Request a Quote', 'طلب عرض سعر'),
 ('seo.quote.desc',
  'وصف الصفحة في جوجل: /quote',
  'Request a quotation from ARFA for construction, MEP, fire protection, medical gas or smart building works in Saudi Arabia.',
  'اطلب عرض سعر من شركة عرفة لأعمال الإنشاءات أو الكهروميكانيك أو الحماية من الحريق أو الغازات الطبية أو المباني الذكية.',
  True),
 ('seo.contactus.title', 'اسم الصفحة في عنوان جوجل: /contactus', 'Contact Us', 'اتصل بنا'),
 ('seo.contactus.desc',
  'وصف الصفحة في جوجل: /contactus',
  'Contact ARFA Construction & Specialized Systems: phone, email, address and the right department for your project.',
  'تواصل مع شركة عرفة للأنظمة المتخصصة: الهاتف والبريد والعنوان والقسم المناسب لمشروعك.',
  True),
 ('seo.contact_team.title', 'اسم الصفحة في عنوان جوجل: /contact-team', 'Contact Us', 'اتصل بنا'),
 ('seo.location.title', 'اسم الصفحة في عنوان جوجل: /location', 'Our Location', 'موقعنا'),
 ('seo.location.desc',
  'وصف الصفحة في جوجل: /location',
  'Find the ARFA Construction & Specialized Systems office on the map with directions and working hours.',
  'موقع مكتب شركة عرفة للأنظمة المتخصصة على الخريطة مع الاتجاهات وساعات العمل.',
  True),
 ('seo.quote_thanks.title', 'اسم الصفحة في عنوان جوجل: /quote/thanks', 'Request Received', 'تم استلام الطلب')]

PAGE_IDS = {'/': 'home',
 '/about': 'about',
 '/our-company': 'our_company',
 '/services': 'services',
 '/projects': 'projects',
 '/news': 'news',
 '/quote': 'quote',
 '/contactus': 'contactus',
 '/contact-team': 'contact_team',
 '/location': 'location',
 '/quote/thanks': 'quote_thanks'}
