# -*- coding: utf-8 -*-
"""Default homepage cards (hero pillars, statistics, why-choose-us) for fresh installs.
Existing databases get them from their previous website configuration instead."""
PAGE = 'home'

ITEMS = [{'section': 'pillar',
  'title_en': 'Structural & Civil Contracting',
  'title_ar': 'المقاولات الإنشائية والمدنية',
  'desc_en': 'Concrete framing, foundations, and heavy structural developments executed strictly to SBC codes.',
  'desc_ar': 'الهياكل الخرسانية والأساسات والأعمال الإنشائية الثقيلة المنفذة وفق كود البناء السعودي.',
  'link_url': '/services',
  'link_label_en': 'Explore Services',
  'link_label_ar': 'استكشف الخدمات',
  'image_file': '/wasm_website/static/src/img/pillar_civil.jpg'},
 {'section': 'pillar',
  'title_en': 'MEP & Mechanical Systems',
  'title_ar': 'الأنظمة الكهروميكانيكية MEP',
  'desc_en': 'Advanced HVAC ducting, plumbing, electrical grid infrastructure, and smart automation.',
  'desc_ar': 'مجاري التكييف المتقدمة، السباكة، شبكات الكهرباء، وأنظمة التحكم الذكي.',
  'link_url': '/services',
  'link_label_en': 'Explore Services',
  'link_label_ar': 'استكشف الخدمات',
  'image_file': '/wasm_website/static/src/img/pillar_mep.jpg'},
 {'section': 'pillar',
  'title_en': 'Turnkey Project Delivery',
  'title_ar': 'تسليم المشاريع مفتاح باليد',
  'desc_en': 'Comprehensive engineering management, interior fitouts, and end-to-end turnkey delivery.',
  'desc_ar': 'إدارة هندسية شاملة وتشطيبات داخلية وتسليم متكامل للمشروع من البداية حتى النهاية.',
  'link_url': '/services',
  'link_label_en': 'Explore Services',
  'link_label_ar': 'استكشف الخدمات',
  'image_file': '/wasm_website/static/src/img/pillar_mgmt.jpg'},
 {'section': 'stat', 'value': '150+', 'title_en': 'Completed Projects', 'title_ar': 'مشروع مكتمل'},
 {'section': 'stat', 'value': '18+', 'title_en': 'Years Experience', 'title_ar': 'عاماً من الخبرة'},
 {'section': 'stat', 'value': '1,200,000+', 'title_en': 'm² Executed Area', 'title_ar': 'م² مساحة منفذة'},
 {'section': 'stat', 'value': '85+', 'title_en': 'Engineers & Specialists', 'title_ar': 'مهندس ومتخصص'},
 {'section': 'why',
  'title_en': 'SBC Code Compliance',
  'title_ar': 'الالتزام بكود البناء السعودي',
  'desc_en': 'Strict adherence to Saudi Building Code specifications across all concrete structural works.',
  'desc_ar': 'التزام صارم بمواصفات كود البناء السعودي في جميع الأعمال الخرسانية والإنشائية.',
  'image_file': '/wasm_website/static/src/img/why_sbc.jpg'},
 {'section': 'why',
  'title_en': 'BIM 3D Project Tech',
  'title_ar': 'تقنيات BIM ثلاثية الأبعاد',
  'desc_en': 'Advanced 3D modeling and clash detection prior to site execution ensuring zero errors.',
  'desc_ar': 'نمذجة ثلاثية الأبعاد متقدمة وكشف التعارضات قبل التنفيذ في الموقع لضمان صفر أخطاء.',
  'image_file': '/wasm_website/static/src/img/why_bim.jpg'},
 {'section': 'why',
  'title_en': 'Owned Heavy Machinery',
  'title_ar': 'معدات ثقيلة مملوكة',
  'desc_en': 'Complete fleet of excavators, cranes, and concrete pumps to accelerate timelines.',
  'desc_ar': 'أسطول متكامل من الحفارات والرافعات ومضخات الخرسانة لتسريع الجداول الزمنية.',
  'image_file': '/wasm_website/static/src/img/why_machinery.jpg'},
 {'section': 'why',
  'title_en': 'Strict Timelines',
  'title_ar': 'التزام صارم بالمواعيد',
  'desc_en': 'Guaranteed project completion within agreed schedule and transparent budget.',
  'desc_ar': 'ضمان إنجاز المشروع ضمن الجدول المتفق عليه وبميزانية شفافة.',
  'image_file': '/wasm_website/static/src/img/why_timelines.jpg'},
 {'section': 'why',
  'title_en': 'Certified Quality Lab',
  'title_ar': 'مختبر جودة معتمد',
  'desc_en': 'Rigorous core testing and ultrasound concrete strength inspection on site.',
  'desc_ar': 'اختبارات دقيقة للعينات وفحص مقاومة الخرسانة بالموجات فوق الصوتية في الموقع.',
  'image_file': '/wasm_website/static/src/img/why_qc.jpg'},
 {'section': 'why',
  'title_en': 'ISO & Site Safety Compliance',
  'title_ar': 'الأيزو والسلامة في المواقع',
  'desc_en': 'Zero-hazard workplace policies adhering to international safety frameworks.',
  'desc_ar': 'سياسات بيئة عمل خالية من المخاطر وفق أطر السلامة الدولية.',
  'image_file': '/wasm_website/static/src/img/why_safety.jpg'}]
